### PR TITLE
Added additional blocks for a tree, some glass, grass, and more

### PR DESCRIPTION
**Pull request by ProxyNeko**
Added two glass blocks, glow bark tree and wood planks (Missing sapling and leaves) and dry grass with names added to the lang file.

 (Some textures missing. Will add in next pull unless requested to make one large PR.)

### CODE REVIEW

**Comment by FairWolf01** [comment]
@MrIbby Can you look through this and merge it soon?

**Comment by ProxyNeko** [comment]
As far as I know it is already merged but sure as long as your happy with it

**Comment by MrIbby** [comment]
It appears the JSONs you added use different spacing than the existing ones. Do you prefer two spaces or four spaces for JSONs?

**Comment by ProxyNeko** [comment]
That is entirely up to you my workspace just uses 4 spaces for everything by default but I can change those if you wish

**Comment by MrIbby** [comment]
Currently, your JSONs have two-space indents, so it'd probably be easier to change them to four spaces rather than changing all of the existing JSONs from four spaces to two spaces.

**Comment by ProxyNeko** [comment]
You are correct Ill fix that n upload in the next pull over the weekend

**Pull request merged**
